pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'tmyfcm-recover' }
    stages {
        stage('Test') {
            options { timeout(time: 50, unit: 'SECONDS') }
            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }// stage test

        stage('Build Image') {
        environment { QUAY = credentials('QUAY_USER') }
            steps {
                dir('shopping-cart-v2') {
                    sh './scripts/include-container-extensions.sh'
                    sh '''
                        ./scripts/build-and-push-image.sh \
                        -u $QUAY_USR \
                        -p $QUAY_PSW \
                        -b $BUILD_NUMBER
                    '''
                }//dir
            }//steps
        }// stage build

        stage('Deploy') {
            environment { QUAY = credentials('QUAY_USER') }
            steps {
                dir('shopping-cart-v2') {
                    script {
                        def status = sh(
                            script: "./scripts/tag-exists-in-quay.sh $QUAY_USR/do400-recover latest",
                                    returnStatus: true
                        )

                        if (status != 0) {
                            error("Tag not found in Quay!")
                        }
                    }//script

                    sh './scripts/redeploy.sh $APP_NAMESPACE'
                }//dir
            }//steps
        }// deploy                          
    }// stages
}// pipeline